#include <iostream>
using namespace std;

class Demo
{
public:
  Demo()
  {
    cout << "This is coming from the Demo object definition of demoObject, automatically generated by the code written inside the Demo() constructor function, which is in turn located in the Demo class declaration, preceding int main()" << endl;
  }
};

int main ()
{
  Demo demoObject;
  return 0;
}
