#include <iostream>
using namespace std;

class Demo
{
public:
  Demo();

};

Demo::Demo()
{
  cout << "This is coming from the Demo object definition of demoObject, automatically generated by the code written inside the Demo() constructor function, which is in turn located in the Demo class declaration, preceding int main()" << endl << endl;

  cout << "The above is no longer true. The Demo() constructor function is no longer an inline function as it was previously. It is only its prototype which is now located inside the Demo class declaration. The constructor is now defined immediately following its class declaration and preceding int main()" << endl;
};

int main ()
{
  Demo demoObject;
  return 0;
}
